version: '3'

services:
  backend:
    build:
      context: ./backend
    command: npm start
    ports:
      - "8080:8080"
  frontend:
    build:
      context: ./thanespgm
    ports:
      - "8000:80"
    volumes:
      - react_build:/app/build
    depends_on:
      - backend
volumes:
  react_build: